name: Swift

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-10.15]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: swift build --verbose

      - name: Run tests
        run: swift test --verbose

  build-linux:
    strategy:
      matrix:
        container: ["swift:5.2.4-bionic", "swiftlang/swift:nightly-5.3-bionic"]

    runs-on: ubuntu-latest
    container: ${{ matrix.container }}

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: swift build --verbose

      - name: Run tests
        run: swift test --enable-test-discovery --verbose

  lint:
    runs-on: macos-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          path: Project

      - name: Checkout SwiftFormat
        uses: actions/checkout@v2
        with:
          repository: nicklockwood/SwiftFormat
          ref: 0.44.13
          path: SwiftFormat

      - name: Run linter
        run: ./SwiftFormat/CommandLineTool/swiftformat --lint ./Project
